// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ServeurIceMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __ServeurIceMP3_h__
#define __ServeurIceMP3_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace serveur
{

class ServeurIceMP3;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::serveur::ServeurIceMP3>&);
::IceProxy::Ice::Object* upCast(::IceProxy::serveur::ServeurIceMP3*);

}

}

namespace serveur
{

class ServeurIceMP3;
bool operator==(const ServeurIceMP3&, const ServeurIceMP3&);
bool operator<(const ServeurIceMP3&, const ServeurIceMP3&);
::Ice::Object* upCast(::serveur::ServeurIceMP3*);
typedef ::IceInternal::Handle< ::serveur::ServeurIceMP3> ServeurIceMP3Ptr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::serveur::ServeurIceMP3> ServeurIceMP3Prx;
void __patch(ServeurIceMP3Ptr&, const ::Ice::ObjectPtr&);

}

namespace serveur
{

class Callback_ServeurIceMP3_ajoutfichier_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIceMP3_ajoutfichier_Base> Callback_ServeurIceMP3_ajoutfichierPtr;

class Callback_ServeurIceMP3_recherche_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIceMP3_recherche_Base> Callback_ServeurIceMP3_recherchePtr;

class Callback_ServeurIceMP3_suppression_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIceMP3_suppression_Base> Callback_ServeurIceMP3_suppressionPtr;

class Callback_ServeurIceMP3_lireMp3_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIceMP3_lireMp3_Base> Callback_ServeurIceMP3_lireMp3Ptr;

class Callback_ServeurIceMP3_stopMp3_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIceMP3_stopMp3_Base> Callback_ServeurIceMP3_stopMp3Ptr;

}

namespace IceProxy
{

namespace serveur
{

class ServeurIceMP3 : virtual public ::IceProxy::Ice::Object
{
public:

    void ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier)
    {
        ajoutfichier(titre, auteur, fichier, 0);
    }
    void ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::Context& __ctx)
    {
        ajoutfichier(titre, auteur, fichier, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_ajoutfichier(titre, auteur, fichier, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_ajoutfichier(titre, auteur, fichier, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_ajoutfichier(titre, auteur, fichier, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_ajoutfichier(titre, auteur, fichier, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier)
    {
        return begin_ajoutfichier(titre, auteur, fichier, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::Context& __ctx)
    {
        return begin_ajoutfichier(titre, auteur, fichier, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ajoutfichier(titre, auteur, fichier, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ajoutfichier(titre, auteur, fichier, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::serveur::Callback_ServeurIceMP3_ajoutfichierPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ajoutfichier(titre, auteur, fichier, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string& titre, const ::std::string& auteur, const ::std::string& fichier, const ::Ice::Context& __ctx, const ::serveur::Callback_ServeurIceMP3_ajoutfichierPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_ajoutfichier(titre, auteur, fichier, &__ctx, __del, __cookie);
    }

    void end_ajoutfichier(const ::Ice::AsyncResultPtr&);
    
private:

    void ajoutfichier(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_ajoutfichier(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string recherche(const ::std::string& titre, const ::std::string& auteur)
    {
        return recherche(titre, auteur, 0);
    }
    ::std::string recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx)
    {
        return recherche(titre, auteur, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_recherche(titre, auteur, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_recherche(titre, auteur, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_recherche(titre, auteur, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_recherche(titre, auteur, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_recherche(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_recherche(titre, auteur, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_recherche(const ::std::string& titre, const ::std::string& auteur)
    {
        return begin_recherche(titre, auteur, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx)
    {
        return begin_recherche(titre, auteur, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_recherche(titre, auteur, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_recherche(titre, auteur, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::serveur::Callback_ServeurIceMP3_recherchePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_recherche(titre, auteur, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_recherche(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::serveur::Callback_ServeurIceMP3_recherchePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_recherche(titre, auteur, &__ctx, __del, __cookie);
    }

    ::std::string end_recherche(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string recherche(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_recherche(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void suppression(const ::std::string& titre, const ::std::string& auteur)
    {
        suppression(titre, auteur, 0);
    }
    void suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx)
    {
        suppression(titre, auteur, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_suppression(titre, auteur, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_suppression(titre, auteur, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_suppression(titre, auteur, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_suppression(titre, auteur, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_suppression(const ::std::string& titre, const ::std::string& auteur)
    {
        return begin_suppression(titre, auteur, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx)
    {
        return begin_suppression(titre, auteur, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_suppression(titre, auteur, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_suppression(titre, auteur, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::serveur::Callback_ServeurIceMP3_suppressionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_suppression(titre, auteur, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_suppression(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::serveur::Callback_ServeurIceMP3_suppressionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_suppression(titre, auteur, &__ctx, __del, __cookie);
    }

    void end_suppression(const ::Ice::AsyncResultPtr&);
    
private:

    void suppression(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_suppression(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string lireMp3(const ::std::string& titre, const ::std::string& auteur)
    {
        return lireMp3(titre, auteur, 0);
    }
    ::std::string lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx)
    {
        return lireMp3(titre, auteur, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_lireMp3(titre, auteur, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_lireMp3(titre, auteur, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_lireMp3(titre, auteur, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_lireMp3(titre, auteur, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_lireMp3(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_lireMp3(titre, auteur, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string& titre, const ::std::string& auteur)
    {
        return begin_lireMp3(titre, auteur, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx)
    {
        return begin_lireMp3(titre, auteur, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_lireMp3(titre, auteur, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_lireMp3(titre, auteur, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::serveur::Callback_ServeurIceMP3_lireMp3Ptr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_lireMp3(titre, auteur, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string& titre, const ::std::string& auteur, const ::Ice::Context& __ctx, const ::serveur::Callback_ServeurIceMP3_lireMp3Ptr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_lireMp3(titre, auteur, &__ctx, __del, __cookie);
    }

    ::std::string end_lireMp3(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string lireMp3(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_lireMp3(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool stopMp3(const ::std::string& nom)
    {
        return stopMp3(nom, 0);
    }
    bool stopMp3(const ::std::string& nom, const ::Ice::Context& __ctx)
    {
        return stopMp3(nom, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_stopMp3(const ::std::string& nom, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_stopMp3(nom, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_stopMp3(const ::std::string& nom, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stopMp3(nom, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stopMp3(const ::std::string& nom, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_stopMp3(nom, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_stopMp3(const ::std::string& nom, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stopMp3(nom, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_stopMp3(const ::std::string& nom, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_stopMp3(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_stopMp3(nom, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string& nom)
    {
        return begin_stopMp3(nom, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string& nom, const ::Ice::Context& __ctx)
    {
        return begin_stopMp3(nom, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string& nom, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopMp3(nom, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string& nom, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopMp3(nom, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string& nom, const ::serveur::Callback_ServeurIceMP3_stopMp3Ptr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopMp3(nom, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string& nom, const ::Ice::Context& __ctx, const ::serveur::Callback_ServeurIceMP3_stopMp3Ptr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopMp3(nom, &__ctx, __del, __cookie);
    }

    bool end_stopMp3(const ::Ice::AsyncResultPtr&);
    
private:

    bool stopMp3(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_stopMp3(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_secure(bool __secure) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_twoway() const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_oneway() const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_batchOneway() const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_datagram() const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_batchDatagram() const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_compress(bool __compress) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_timeout(int __timeout) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ServeurIceMP3> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<ServeurIceMP3*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace serveur
{

class ServeurIceMP3 : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void ajoutfichier(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::std::string recherche(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void suppression(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::std::string lireMp3(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool stopMp3(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace serveur
{

class ServeurIceMP3 : virtual public ::IceDelegate::serveur::ServeurIceMP3,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void ajoutfichier(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string recherche(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void suppression(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string lireMp3(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool stopMp3(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace serveur
{

class ServeurIceMP3 : virtual public ::IceDelegate::serveur::ServeurIceMP3,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void ajoutfichier(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string recherche(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void suppression(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string lireMp3(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool stopMp3(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace serveur
{

class ServeurIceMP3 : virtual public ::Ice::Object
{
public:

    typedef ServeurIceMP3Prx ProxyType;
    typedef ServeurIceMP3Ptr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void ajoutfichier(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___ajoutfichier(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string recherche(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___recherche(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void suppression(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___suppression(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string lireMp3(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___lireMp3(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool stopMp3(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___stopMp3(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const ServeurIceMP3& l, const ServeurIceMP3& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ServeurIceMP3& l, const ServeurIceMP3& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace serveur
{

template<class T>
class CallbackNC_ServeurIceMP3_ajoutfichier : public Callback_ServeurIceMP3_ajoutfichier_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ServeurIceMP3_ajoutfichier(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_ajoutfichier<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_ajoutfichier<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_ajoutfichier<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_ajoutfichier<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ServeurIceMP3_ajoutfichier : public Callback_ServeurIceMP3_ajoutfichier_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ServeurIceMP3_ajoutfichier(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_ajoutfichier<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_ajoutfichier<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_ajoutfichier<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_ajoutfichierPtr
newCallback_ServeurIceMP3_ajoutfichier(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_ajoutfichier<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ServeurIceMP3_recherche : public Callback_ServeurIceMP3_recherche_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_ServeurIceMP3_recherche(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_recherche(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_ServeurIceMP3_recherchePtr
newCallback_ServeurIceMP3_recherche(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_recherche<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_recherchePtr
newCallback_ServeurIceMP3_recherche(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_recherche<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ServeurIceMP3_recherche : public Callback_ServeurIceMP3_recherche_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_ServeurIceMP3_recherche(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_recherche(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ServeurIceMP3_recherchePtr
newCallback_ServeurIceMP3_recherche(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_recherche<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_recherchePtr
newCallback_ServeurIceMP3_recherche(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_recherche<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_ServeurIceMP3_suppression : public Callback_ServeurIceMP3_suppression_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ServeurIceMP3_suppression(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_suppression<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_suppression<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_suppression<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_suppression<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ServeurIceMP3_suppression : public Callback_ServeurIceMP3_suppression_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ServeurIceMP3_suppression(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_suppression<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_suppression<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_suppression<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_suppressionPtr
newCallback_ServeurIceMP3_suppression(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_suppression<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ServeurIceMP3_lireMp3 : public Callback_ServeurIceMP3_lireMp3_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_ServeurIceMP3_lireMp3(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_lireMp3(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_ServeurIceMP3_lireMp3Ptr
newCallback_ServeurIceMP3_lireMp3(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_lireMp3<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_lireMp3Ptr
newCallback_ServeurIceMP3_lireMp3(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_lireMp3<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ServeurIceMP3_lireMp3 : public Callback_ServeurIceMP3_lireMp3_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_ServeurIceMP3_lireMp3(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_lireMp3(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ServeurIceMP3_lireMp3Ptr
newCallback_ServeurIceMP3_lireMp3(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_lireMp3<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_lireMp3Ptr
newCallback_ServeurIceMP3_lireMp3(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_lireMp3<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_ServeurIceMP3_stopMp3 : public Callback_ServeurIceMP3_stopMp3_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_ServeurIceMP3_stopMp3(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_stopMp3(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_ServeurIceMP3_stopMp3Ptr
newCallback_ServeurIceMP3_stopMp3(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_stopMp3<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ServeurIceMP3_stopMp3Ptr
newCallback_ServeurIceMP3_stopMp3(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIceMP3_stopMp3<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ServeurIceMP3_stopMp3 : public Callback_ServeurIceMP3_stopMp3_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_ServeurIceMP3_stopMp3(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::serveur::ServeurIceMP3Prx __proxy = ::serveur::ServeurIceMP3Prx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_stopMp3(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ServeurIceMP3_stopMp3Ptr
newCallback_ServeurIceMP3_stopMp3(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_stopMp3<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ServeurIceMP3_stopMp3Ptr
newCallback_ServeurIceMP3_stopMp3(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIceMP3_stopMp3<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
