// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ServeurIceMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package serveur;

public interface _ServeurIceMP3OperationsNC
{
    void ajoutfichier(String titre, String auteur, String fichier);

    String recherche(String titre, String auteur);

    String[] rechercheTitre(String titre);

    String[] rechercheAuteur(String auteur);

    void suppression(String titre, String auteur);

    String lireMp3(String titre, String auteur);

    String lireMp3ParFichier(String fichier);

    boolean stopMp3(String nom);
}
