// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ServeurIceMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package serveur;

public final class ServeurIceMP3Holder extends Ice.ObjectHolderBase<ServeurIceMP3>
{
    public
    ServeurIceMP3Holder()
    {
    }

    public
    ServeurIceMP3Holder(ServeurIceMP3 value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof ServeurIceMP3)
        {
            value = (ServeurIceMP3)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _ServeurIceMP3Disp.ice_staticId();
    }
}
